[LogConfiguration]
; This file controls how the log entires look. Editing these can cause logs to become nonfunctional, so be careful.
; Each logtype will mention what data is available and what their formatter is.

; %1 = Event Time
; %2 = Area Name
; %3 = Client IPID
; %4 = Client ID
; %5 = Character Name
; %6 = Out-Of-Courtroom Name
; %7 = Message

ic="[%1][%2][IC]{%3}[%4]%5(%6): %7"

; %1 = Event Time
; %2 = Area Name
; %3 = Client IPID
; %4 = Client ID
; %5 = Character Name
; %6 = Out-Of-Courtroom Name
; %7 = Message

ooc="[%1][%2][OOC]{%3}[%4]%5(%6): %7"

; %1 = Event Time
; %2 = Area Name
; %3 = Character Name
; %4 = Out-Of-Courtroom Name
; %5 = Command Name
; %6 = Command Arguments
; %7 = Client IPID
cmd="[%1][%2][CMD][%7][%3(%4)]/%5 %6"

; %1 = Event Time
; %2 = Moderator User ID
; %3 = Kicked Client User ID
kick="[%1][%2][KICK][%3]"

; %1 = Event Time
; %2 = Moderator User ID
; %3 = Banned Client User ID
; %4 = Ban Duration
ban="[%1][%2][BAN][%3][%4]"

; %1 = Event Time
; %2 = Area Name
; %3 = Client IPID
; %4 = Client ID
; %5 = Character Name
; %6 = Out-Of-Courtroom Name
modcall="[%1][%2][MODCALL][%3][%4][%5(%6)]"

; %1 = Event Time
; %2 = IP Address
; %3 = Client IPID
; %4 = Client HWID
connect="[%1][CONNECT][%2][%3][%4]"