#pragma once

#include "broadcaster.h"
#include "config_manager.h"
#include "game/music.h"
#include "network/packet.h"

#include <QHash>
#include <QMap>
#include <QObject>
#include <QPair>

#include <optional>

namespace kenji
{
class MusicManager : public QObject
{
  Q_OBJECT

public:
  /**
   * @brief Constructor for the server-wide musiclist manager.
   *
   * @param Copy of the server musiclist generated by ConfigManager::musiclist();
   */
  MusicManager(Broadcaster &f_broadcaster, const QStringList &f_cdns, const QList<theory::MusicPlaylist> &f_root_list, QObject *parent = nullptr);

  /**
   * @brief Destructor for the server-wide musiclist manager.
   */
  virtual ~MusicManager();

  /**
   * @brief Returns the musiclist associated with the area.
   */
  QList<theory::MusicPlaylist> playlists(int f_area_id);

  /**
   * @brief Adds a new area to the music_manager.
   *
   * @param f_area_id ID of the new area being added.
   *
   * @return Returns false if registering the area fails.
   */
  bool registerArea(int f_area_id);

  /**
   * @brief Validates the song candidate to be played. If validation fails, false is returned.
   *
   * @param f_song_name The song to be played. Can be an http/https stream or a local file.
   *
   * @param f_approved_cdns A list of approved remote content sources.
   *
   * @return Wether or not the song can be played or added.
   */
  bool validateSong(const QString &f_song_name, const QStringList &f_approved_cdns);

  /**
   * @brief Attempts to add the new song to the custom musiclist.
   *
   * @param f_song_name Friendly name shown in the clients musiclist.
   *
   * @param f_real_name Real name/url of the file.
   *
   * @param f_duration Playtime of the musicfile in seconds.
   *
   * @param f_area_id Area id of the clients current area.
   *
   * @return Returns true on success, false on fail.
   */
  bool addCustomSong(const QString &f_song_name, const QString &f_real_name, theory::TrackLength f_duration, int f_area_id);

  /**
   * @brief Attempts to add the new category to the custom musiclist.
   *
   * @param f_category_name Category name candidate.
   *
   * @return Returns true on saccess, false on fail.
   */
  bool addCustomCategory(const QString &f_category_name, int f_area_id);

  /**
   * @brief Removes either a song or a category from the custom list.
   *
   * @param Name of the category or song to remove
   *
   * @return True on success, false on failure.
   */
  bool removeCustomMusic(const QString &f_songcategory_name, int f_area_id);

  /**
   * @brief Toggles wether the root list is included for this area.
   * This also delets the custom llist if it was enabled prior.
   *
   * @return Current state of the music list.
   */
  bool toggleCustomMusicEnabled(int f_area_id);

  /**
   * @brief Removes conflicting songnames from the custom list.
   *
   * @param f_area_id Id of the area this is invoked in.
   */
  void sanitiseCustomMusicList(int f_area_id);

  /**
   * @brief Removes all entries from the custom list.
   * @param f_area_id Id of the area custom list.
   */
  void clearCustomMusicList(int f_area_id);

  /**
   * @brief Finds a track.
   * @param f_file_name The track's file name.
   * @param f_area_id Area being searched.
   * @return The track ir nothing.
   */
  std::optional<theory::MusicTrack> findTrack(const QString &f_file_name, int f_area_id);

public Q_SLOTS:

  /**
   * @brief Updates the root musiclist and CDN list.
   */
  void reloadRequest();

  /**
   * @brief Sends the area's musiclist to a client.
   */
  void userJoinedArea(int f_area_index, int f_user_id);

private:
  Broadcaster &m_broadcaster;

  void broadcastMusicList(int f_area_id);

  bool rootContainsTrack(const QString &f_file_name) const;

  /**
   * @brief Contains all custom lists of all areas in the server.
   */
  QHash<int, QList<theory::MusicPlaylist>> m_custom_lists;

  /**
   * @brief Server musiclist shared among all areas.
   */
  QList<theory::MusicPlaylist> m_root_list;

  /**
   * @brief Wether the global musiclist is prepend and validation when adding custom music.
   */
  QHash<int, bool> m_global_enabled;

  /**
   * @brief Contains all server approved content sources.
   */
  QStringList m_cdns;
};
} // namespace kenji
